<!doctype html>
<html lang="<?= ds_lang() ?>" data-bs-theme="light">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title><?= e($title ?? app_name()) ?></title>

  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800&family=Noto+Sans+Georgian:wght@400;500;600;700;800&display=swap" rel="stylesheet">

  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
  <link href="/assets/fonts/bpg-arial-caps/css/bpg-arial-caps.min.css" rel="stylesheet">
  <link href="/assets/css/design-system.css" rel="stylesheet">
</head>
<body class="ds-document-body">

<main class="ds-document-page">
  <?= $content ?>

  <!-- Same two lines as InvoiceController::pdfFooterHtml() (the real PDF's
       own running footer) — debt notice, then the "Generated by X" credit
       link, the page's only link (4.77 in handoff.md). Inside the A4 sheet
       itself, not below it (4.79) — .ds-document-page is a flex column so
       this sits pinned to the sheet's own bottom edge, not the browser
       window's. -->
  <footer class="ds-document-footer">
    <div class="ds-document-footer-notice"><?= t('inv.pdf_debt_notice') ?></div>
    <div class="ds-document-footer-credit">
      <?php
        $docUrl = app_url();
        echo $docUrl !== ''
            ? t('inv.pdf_generated_by', '<a href="' . e($docUrl) . '">' . e(app_name()) . '</a>')
            : t('inv.pdf_generated_by', e(app_name()));
      ?>
    </div>
  </footer>
</main>

<?= $scripts ?? '' ?>
</body>
</html>
